### ISSUE TITLE
error config

### ISSUE THREAD

**Issue by zirain** [tuffk/Logstash-output-to-Azure-Blob#31]
hi, 
after install the latest logstash-output-azure
with config like:
```
output {
    stdout {}
    azure {
      storage_account_name => ""
      storage_access_key  => ""
      contianer_name  => ""
    }
}
```
get error as follow:
[ERROR][logstash.outputs.logstashazurebloboutput] Unknown setting 'contianer_name' for azure

**Comment by zirain** [comment]
fix when use an global azure storage account

**Comment by puneethboinapally-gep** [comment]
Hi Zirain ,I am facing the same issue. 
What did you do to fix this ? What does global Azure storage Account mean ?

**Comment by guregini** [comment]
"cont**ia**ner_name" should be "cont**ai**ner_name"
